
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberdemos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KuberDemo
  template:
    metadata:
      labels:
        app: KuberDemo
    spec:
      containers:
      - name: kuberdemo
        image: webwithcontainer.azurecr.io/wallpaperrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: wallpapersn

---
apiVersion: v1
kind: Service
metadata:
  name: kuberdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: KuberDemo